/* CREATE TABLE */
CREATE TABLE IF NOT EXISTS TABLE_NAME(
  id INT(11), 
  NOME VARCHAR(100), 
  DATA_DE NASCIMENTO VARCHAR(100), 
  CATEGORIA VARCHAR(100), 
  GRUPO_DE ATENDIMENTO VARCHAR(100), 
  DATA_DA VACINAÇÃO / D1 VARCHAR(100), 
  VACINA VARCHAR(100), 
  LOTE VARCHAR(100), 
  VACINADOR VARCHAR(100), 
  ESTABELECIMENTO VARCHAR(100), 
  EQUIPE VARCHAR(100)
);
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    1, 'EXPEDITA RODRIGUES MARREIRA PONTES', 
    '12/07/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    2, 'JOSE DE FREITAS BRANDAO', '14/12/36', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    3, 'MANOEL PEREIRA DUTRA', '05/09/35', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    4, 'MARIA MARTA DE FREITAS', '04/04/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    5, 'JOSE LINO MARQUES ', '16/10/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    6, 'RITA DE CASSIA ANDRADE', '03/09/45', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    7, 'MANOEL VERISSIMO DO NASCIMENTO', 
    '06/10/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    8, 'FRANCISCO JANUARIO DE ARAUJO', 
    '03/12/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    9, 'CLAUDIO RODRIGUES DA SILVA', 
    '01/12/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    10, 'ANTONIA MARIA MARQUES', '28/12/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    11, 'MARIA ANTONIETA DE ARAUJO SOUZA', 
    '18/08/32', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    12, 'MARIA DALVA FERREIRA', '14/07/27', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    13, 'MARIA GUILHERMINA DA SILVA', 
    '06/05/20', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    14, 'ALBERTINA DE FREITAS VASCONCELOS', 
    '06/01/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    15, 'JOAO ESTEVAM DE FREITAS', '03/09/38', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    16, 'ANTONIA ALICE DA ROCHA', '13/06/26', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    17, 'DAGILSA FERREIRA DE FREITAS', 
    '03/03/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    18, 'FRANCISCA ZILDAMIR ALVES ARAUJO', 
    '04/10/38', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    19, 'MARIA DE LOURDES DE JESUS', 
    '15/10/26', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    20, 'MARIA VALDIRA DA SILVA', '29/04/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 3'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    21, 'ISABEL DE SOUSA MUNIZ', '01/08/22', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    22, 'JORGE DE SOUSA', '23/11/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    23, 'ALFA LOPES MARANHAO', '27/05/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    24, 'DALVINA MUNIZ DE SOUSA VASCONCELOS', 
    '03/09/23', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    25, 'MARIA ILCA LEITAO DE MENEZES', 
    '02/01/25', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    26, 'RAIMUNDA EULINA BRANDAO', '21/04/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    27, 'FRANCISCO MUNIZ DE FREITAS', 
    '24/07/25', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    28, 'EXPEDITA FONTELES DE JESUS', 
    '19/08/28', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    29, 'CANDIDA MARIA DE FARIAS', '04/09/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    30, 'FRANCISCO OSWALDO DE ALBUQUERQUE', 
    '08/06/32', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    31, 'FRANCISCA MARIA DE VASCONCELOS', 
    '13/04/18', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    32, 'MARIA ODETE DE FARIAS', '04/05/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    33, 'MARIA CONCEICAO SOUZA VASCONCELOS', 
    '24/10/36', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    34, 'MARIA ALICE DE ARAUJO', '06/08/28', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    35, 'PEDRO FERREIRA PINTO', '03/02/35', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    36, 'MARIA ACLINA NASCIMENTO', '12/10/25', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    37, 'BENEDITO PEIXOTO DA MOTA', '01/01/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    38, 'MARIA ELVIRA GOMES', '28/12/26', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    39, 'RITA DE CASSIA DO NASCIMENTO', 
    '13/05/27', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    40, 'CECILIA MARIA SECUNDO DOS SANTOS', 
    '22/11/30', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 2'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    41, 'MARINA COSTA DE VASCONCELOS', 
    '28/01/30', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    42, 'MARIA JOSE DO NASCIMENTO', '17/08/30', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    43, 'MARIA FERREIRA DA CRUZ', '22/01/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    44, 'FRANCISCO TOMAZ LOURENCO', '23/07/27', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    45, 'LUIZ GONZAGA ALBUQUERQUE', '21/06/26', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    46, 'MANOEL MESSIAS DE FREITAS', 
    '05/03/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    47, 'BENTO MARQUES DE SOUSA', '13/11/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    48, 'MANOEL MESSIAS VASCONCELOS', 
    '15/01/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    49, 'ALEXANDRINA DE ARAUJO MUNIZ', 
    '29/09/40', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    50, 'MARIA DO SOCORRO SOUSA', '19/05/39', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    51, 'MARIA DO SOCORRO DE SOUSA', 
    '29/06/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    52, 'MARIA DO SOCORRO DE SOUZA VASCONCELOS', 
    '11/10/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    53, 'CECILIA PINTO MUNIZ RODRIGUES', 
    '13/08/27', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    54, 'MARIA NOEME DE VASCONCELOS', 
    '26/10/42', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    55, 'RAIMUNDA MUNIZ DE VASCONCELOS', 
    '16/05/30', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    56, 'MARIA LIZETE VASCONCELOS', '22/06/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    57, 'MARINA BERNARDA DA COSTA', '03/07/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    58, 'RAIMUNDO ANDRADE PESSOA', '03/06/33', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    59, 'MARIA DO CARMO MUNIZ', '30/06/39', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    60, 'GERALDA ADELIA PINTO VASCONCELOS', 
    '06/07/38', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'LEILA CECILIA SOUSA LIMA', 'CS DR EDIJANIR GARCIA DA SILVA', 
    'SEDE 1'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    61, 'FRANCISCO MARTINS DE OLIVEIRA', 
    '26/06/41', 'FAIXA ETARIA', '75 A 79 ANOS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    62, 'ELVIRA LIBRADA DE SOUSA', '12/06/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    63, 'LUZIA MARTA DA SILVA SILVEIRA', 
    '29/07/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    64, 'MARIA NAIR DE SOUSA', '14/11/37', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    65, 'MARIA ERMILTA DE PAULA NASCIMENTO', 
    '03/03/32', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    66, 'MARIA DO CARMO VASCONCELOS ALBUQUERQUE', 
    '22/06/44', 'FAIXA ETARIA', '75 A 79 ANOS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    67, 'RITA TEIXEIRA DOS SANTOS', '02/01/40', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    68, 'RITA MARIA DA CONCEICAO', '20/12/19', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    69, 'MARIA BEZERRA DE SOUSA', '01/01/30', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    70, 'VICENTE PEREIRA DO NASCIMENTO', 
    '25/08/25', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'GLAIANE SOUSA MORAES', 'UBSF IZAIAS JOSE DO NASCIMENTO', 
    'TUCUNS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    71, 'JOSE EURICO PESSOA ANDRADE', 
    '18/05/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    72, 'MARIA DIONISIA RODRIGUES', '13/10/38', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    73, 'JOSE FARIAS DE MENEZES', '05/11/42', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    74, 'RAIMUNDO NONATO DE SOUSA', '26/04/30', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    75, 'MARIA JOSE DE VASCONCELOS', 
    '27/08/15', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    76, 'PAULINA MARIA DA CONCEICAO', 
    '17/08/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    77, 'NOEME IRACI DA COSTA', '27/09/28', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    78, 'RAIMUNDO ARAUJO SILVEIRA', '13/12/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    79, 'RAIMUNDO FABIAO DE SOUSA', '08/03/33', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    80, 'MARTINHO RAIMUNDO DE VASCONCELOS', 
    '12/11/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'EMANOEL TIAGO DE SOUSA', 'UBSF FRANCISCO TEIXEIRA DE VASCONCELOS', 
    'PITOMBEIRAS'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    81, 'NILCE RAMOS DE SOUSA', '13/09/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    82, 'SABINO BERNARDINO DO NASCIMENTO', 
    '01/09/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    83, 'MARIA TARGINO DE LIMA', '01/05/35', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    84, 'MARIA COSMA DA SILVEIRA', '23/02/44', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    85, 'MANOELA FERREIRA DA SILVA', 
    '04/07/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    86, 'FRANCISCO ASSIS FONTELES DA SILVEIRA', 
    '05/07/30', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    87, 'ELVIRA DIAS DA FONSECA', '17/08/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    88, 'JOSE MILTON DE VASCONCELOS', 
    '28/08/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    89, 'MARIA LIVRAMENTO BRANDAO', '19/06/33', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    90, 'JOSE EDILSON DE SOUZA', '11/07/36', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LIDIANE VITAL DA SILVA', 'UBSF PEDRO ADAMASTOR DE ARAUJO', 
    'CORREGUINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    91, 'MANOEL MARREIRO DE VASCONCELOS', 
    '27/08/25', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    92, 'MARIA GOMES MARREIROS', '26/02/26', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    93, 'PEDRO ANTONIO DO NASCIMENTO', 
    '07/06/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    94, 'ANTONIO SALES DE VASCONCELOS', 
    '30/01/30', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    95, 'LUCIA AURELIA DE SOUSA ARAUJO', 
    '15/08/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    96, 'RITA MARIA MARQUES', '24/03/33', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    97, 'ARTUR ALEXANDRE FERREIRA', '20/06/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    98, 'MARIA FRANCISCA DE JESUS', '17/12/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    99, 'ANTONIO JOSE DE FREITAS', '03/11/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    100, 'MARIA DO SOCORRO ALVES', '16/07/44', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'LOURDES NEIDE BRANDAO', 'UBSF GERALDO ALVES DE MENEZES', 
    'BELEM'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    101, 'EXPEDITO PINTO SILVEIRA', '24/05/40', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    102, 'ANTONIA MARQUES SILVEIRA', 
    '31/08/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    103, 'JOAO DE SOUZA ARAUJO', '31/05/35', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    104, 'FRANCISCO GERALDO DAS CHAGAS', 
    '17/11/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    105, 'NEUZA ARAUJO SILVEIRA', '28/08/28', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    106, 'MANOEL PEREIRA DUTRA', '18/09/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    107, 'ADAIL VASCONCELOS CRUZ', '06/08/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    108, 'JOSE ANTONIO DE SOUSA', '08/08/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    109, 'LOURENCO MARINHO DA SILVA', 
    '16/12/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    110, 'ZUMIRA ALICE DE VASCONCELOS', 
    '04/06/32', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'SILVILENE SANTOS LOPES SILVEIRA', 
    'UBSF MARIA DORALICE DA COSTA', 
    'POÇO DOCE'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    111, 'MANOEL FABIAO DE PAULO', '25/11/42', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    112, 'LIBRADA MARIA DE SOUSA', '10/12/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    113, 'EDILSON PEDRO DA SILVA', '17/04/40', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    114, 'GERALDO MARQUES DA ROCHA', 
    '01/10/36', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    115, 'MARIA AUGUSTA DE SOUSA SILVA', 
    '29/08/38', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    116, 'PAULO RODRIGUES DA SILVA', 
    '27/06/27', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    117, 'IDELZUITE MARIA DE VASCONCELOS GOMES', 
    '20/12/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    118, 'GERALDO RAIMUNDO DE MARIA', 
    '18/10/24', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    119, 'MARIA AEROLIZA VASCONCELOS', 
    '30/01/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    120, 'JOVINO PINTO ARAUJO', '21/05/17', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'WANDERLI ERLANDIA DE SOUSA', 'POSTO DE SAUDE DE CAJUEIRINHO', 
    'CAJUEIRINHO'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    121, 'EUFRAZIO ALCANTARA SOUZA', 
    '20/06/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    122, 'MARIA JOSE DA COSTA', '10/10/35', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    123, 'MARIA MARQUES DE MORAIS', '26/07/37', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    124, 'ODETE RODRIGUES DE ANDRADE ARAUJO', 
    '20/05/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    125, 'DOMINGOS RODRIGUES CHAVES', 
    '16/10/38', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    126, 'MARIA CONCEICAO DE FREITAS', 
    '14/11/41', 'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    127, 'JOSE EUDES DE SOUSA', '11/03/43', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    128, 'MARIA DO CARMO DE ARAUJO', 
    '02/05/36', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    129, 'ONOFRE MARQUES DE SOUSA', '12/06/36', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    130, 'RAIMUNDO GERALDO DE OLIVEIRA', 
    '16/08/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'MAIRTON MAGNO MARQUES DE FREITAS', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    131, 'ALFREDO FERREIRA DA CRUZ', 
    '26/08/28', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    132, 'MANOEL JOAQUIM DE VASCONCELOS', 
    '28/03/36', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    133, 'MARIA FERREIRA DA CRUZ', '27/08/38', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    134, 'ROSA MARIA VASCONCELOS DOS SANTOS', 
    '18/10/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    135, 'MARIA APARECIDA DO NASCIMENTO', 
    '10/04/43', 'FAIXA ETARIA', '75 A 79 ANOS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    136, 'MARIA FERREIRA DO LIVRAMENTO', 
    '10/11/20', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    137, 'MANOEL DE PADUA GUIMARAES', 
    '01/07/35', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    138, 'JOSE VALDI DA SILVA', '10/01/40', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    139, 'ANTONIO VALCI VIDAL', '16/06/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    140, 'CELESTINA RODRIGUES CHAVES', 
    '27/10/37', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '28/01/21', 'COV19-AZE', '4120Z005', 
    'SANDRA NATALIA FERREIRA DE ARAUJO', 
    'UBSF CONSTANCIA DE SOUZA MUNIZ', 
    'PARAGUAI'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    141, 'MARIA JOSE DE ARAUJO ', '19/02/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    142, 'RAIMUNDA NONATA DA SILVA', 
    '29/04/33', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    143, 'JOSE DEDITE DA SILVA', '18/02/37', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    144, 'MANOEL SOARES DE ALBUQUERQUE', 
    '07/12/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    145, 'MARIA NEUZA DE SOUZA', '10/05/37', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    146, 'FRANCISCO MARQUES DE OLIVEIRA', 
    '24/09/34', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    147, 'ANTONIO JOAO DO NASCIMENTO', 
    '27/03/31', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    148, 'ADELIA FERREIRA DOS SANTOS', 
    '16/08/27', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    149, 'ANA SILVEIRA ARAUJO', '28/12/32', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    150, 'MARIA POLICARPO DE SOUSA', 
    '22/08/29', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'INGRIDE CLARA SILVA ROCHA', 'POSTO DE SAUDE DE CAICARA', 
    'CAICARA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    151, 'MARIA DAS NEVES DE ALEXANDRIA', 
    '05/08/25', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    152, 'MARIA DE NAZARE GOMES', '24/07/29', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    153, 'ROSA GONCALVES ARAUJO', '31/10/27', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    154, 'FRANCISCA BARROS TRINDADE', 
    '10/10/39', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    155, 'MARIA NILSE FERREIRA', '08/07/43', 
    'FAIXA ETARIA', '75 A 79 ANOS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    156, 'ANGELINA TEIXEIRA DE CARVALHO', 
    '07/04/22', 'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    157, 'JOAO PIRES CHAVES', '23/09/34', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    158, 'MARIA MEDEIROS CHAVES', '04/01/31', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    159, 'LUIZA MARIA DE JESUS', '10/04/27', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  (
    160, 'MARIA MULATA DE SOUSA', '25/02/28', 
    'FAIXA ETARIA', '80 ANOS OU MAIS', 
    '29/01/21', 'COV19-AZE', '4120Z005', 
    'DEBORA LIMA BRANDAO', 'UBSF FRANCISCO DIAS DOS SANTOS', 
    'PREA'
  );
/* INSERT QUERY */
INSERT INTO TABLE_NAME(
  id, NOME, DATA_DE NASCIMENTO, CATEGORIA, 
  GRUPO_DE ATENDIMENTO, DATA_DA VACINAÇÃO / D1, 
  VACINA, LOTE, VACINADOR, ESTABELECIMENTO, 
  EQUIPE
) 
VALUES 
  ('');
