Nome	                Tipo            Primaria
id   	                int(11)         SIM
vac_vacinado 	        varchar(200)
vac_data_nascimento 	date
vac_categoria       	varchar(200)
vac_grupo_atendimento 	varchar(200)
vac_data_vacinacao 	    date
vac_fase 	            varchar(20)
vac_dose 	            varchar(20)
vac_vacina 	            varchar(50)
vac_lote 	            varchar(50)
vac_vacinador 	        varchar(200)
vac_estabelecimento 	varchar(200)
vac_equipe          	varchar(100) 